apiVersion: v1
kind: Service
metadata:
  name: lab1
  labels:
    app: lab1
spec:
  selector:
    app: lab1

  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30010

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: lab2
  labels:
    app: lab2
spec:
  selector:
    app: lab2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
