apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
spec:
  selector:
    matchLabels:
      app: lab1
  replicas: 1
  template:
    metadata:
      name: lab1
      labels:
        app: lab1
    spec:
      containers:
        - name: lab1
          image: bloodysoon/laborator_1:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2
spec:
  selector:
    matchLabels:
      app: lab2
  replicas: 1
  template:
    metadata:
      name: lab2
      labels:
        app: lab2
    spec:
      containers:
        - name: lab2
          image: bloodysoon/laborator_2:latest
