name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bloodysoon
          password: madrid12489988

      - name: Build and push database image
        uses: docker/build-push-action@v2
        with:
          context: ./Lab1-bd
          file: ./Lab1-bd/Dockerfile
          tags: bloodysoon/laborator_1:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./Lab2-front
          file: ./Lab2-front/Dockerfile
          tags: bloodysoon/laborator_2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Set up Kubeconfig
        run: |
          echo "apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EVXhOakU0TXpNMU0xb1hEVE0wTURVeE5ERTRNek0xTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzg1CkVjbC8rNHErdGU0ZnhKbkliT3BBcGZHZDYvdVhwUUQwWE5oUVgranBaYzZEcGo5NjJoS2R4VnBDNUlaRFN3SngKUWtBcG42OGpnWGo5cjF5dnQ0RkVoN1RZUHNTSUhrOVhyRGc5R1BaTGw3aldjUUxBRzRrL1lpemZFTHZnNFVsTQpUWHc3T3QzNUpwT3B1NWFNTWZwMVJHTmwvOVdybFVUbFZSSk1wT2ovQ2NsUzNkeS9MeUxkcC85ZytwYzBtdDlCCi8rT0R6OGRyUW9pQlRRTXJVUHVLQjl3eFg0OXk2NTZhWmpjUHk3TWhuZUwvTHQyc2hWcndzWndvdVRBOXNKa2wKRFVwNEx5NWxOdEtMczRiY0tMdS9IaG9CcEx4U3JqMWJ1Z3hubmhTRmczb3FUM2Z5SXI5NElRUE9NWmV0Vk15bQpia3RaWEYwTUF3MS84Ym5paXdNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIMlc2N25YWHZTV2o0TnNraVB1QlA1SnpCd1VNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSEo5bjdSQSs2UGJHK1JtQmZFNAo2SmRaMUlMZ0NuR040NzFXMVpzeGppNUR0K3J0YjdMNGVQZ0Q4bEs1UjN4QkV3OWZXNzJhdEw5ODVJbURoUnBpCmJ4YkJoVHF6TFlaei9ybnhQUVJFSitxYk9BV3pZOWNobjI3eVU3R3hNNGk1OWpveG1YWHh6Zm4vc0JzUVZZazkKR2JJR2c0WHVRN3BUYVNVUzQrbmRXMGFWUXpJMUsxbDFQZ2hZbEI3UTM2ZnBwd0g1bVh4RTM2NUgyL3dmeEg4RgpySWtMb1k2N3Y1OUxkWU92Sms1SS84ODkzeklqY0xSVkNGVUlUeXBQb1pkTldMQ29ZNmt6Z2xzUmVhZVJJSmRxClRQbmVYbURBcGxmc3BxcE1WSllaTnFWNVFybVE2aVdDYjZzUkNYMk1FdmJzUGJnaUlmSFJITWl2eThCWFFHeS8KdDhnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWlxZ0F3SUJBZ0lJVlBBL0VTZCtCOFV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMU1UWXhPRE16TlROYUZ3MHlOVEExTWpReE56RXhNRGxhTURZeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sc3dHUVlEVlFRREV4SmtiMk5yWlhJdFptOXlMV1JsCmMydDBiM0F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGV0L0gvRkIzb0xkSFgKOGhyczBJU25KZjNGMjRuL2R3TlZJMGdEM2RaTmVKQ3lDclBQUTU2OVloMkxWZmpGWHdaYWR1Vm55aEl4ZytuMworbnl2TnZSaGc3ODYrMnowMjJnNGgvMkVHU0pzRmdqMjV1YU5hNVZDcldmaExpODk5UThqK0JyUG5kRExNc2pWCkV1blVOM3Q3NU82M0JtNzJuVDRHSGp1ckVOWTNDalBzby9Ka2Y5M0k0eVNGU1Fnc21pQzRIeXdudXkxYWx0QVAKcjd0aVlSZjFWaU9BL1kybmJQSWdiYUtURVAzMUtJZWlTOWtEVEg3TzBWbWZhdmlFR01US3kxUGFnYjE3Q1ZubQpZckZiNEJZVEU3ZzZueHdUdWNFdDc2OC93YzZ4QVlRYnNNK2hiUzZDbGlXZWNUSmsyVEMrVHdsR05aN29UbldBCjg5TzNWSmV2QWdNQkFBR2pkVEJ6TUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZIMlc2N25YWHZTV2o0TnNraVB1QlA1Sgp6QndVTUIwR0ExVWRFUVFXTUJTQ0VtUnZZMnRsY2kxbWIzSXRaR1Z6YTNSdmNEQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBY3lDU3hSRWRJVHhsZDU3NDI3RXk0eXUzMUdRRmYwMUhRekRxcjBjbmJmR3QrdTM1Und1dlNWelQKbjZ0T2ZIY0xqS3REUTdSaVBJRkZrQnhKeWJaeEhNVzVraHdPLy95YnZ5WURLU1o4andTRGh5NDMvVzJTdmVkOQpDQThRSUs4UWdzYmIrZGtlTHNBaWZaUkRSbjdHR09PZ1pCTlEvdlppNjloTm8wNFRUYW01SDlYbVpYZnlWbUt3ClZ3anZ2SlZLTUR5UFBBd2tJdDVlTm5yeXVHOTN5WlF2VmVIQTlmMHBTTTBybnRXeWlNenVqOGhua0RoQWxWTGYKd3VoSUFCR2grNTYzZVFXY054T0dyQmRUeFBUb3FncGlOeWo5VE1JWDBqdFBrd05mT09KVytFZWRUM0c1TFRHdApmamNrRnJ6NDFmMmJuNUpNRGd2VGhEMzVQNjN0T0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBM3JmeC94UWQ2QzNSMS9JYTdOQ0VweVg5eGR1Si8zY0RWU05JQTkzV1RYaVFzZ3F6CnowT2V2V0lkaTFYNHhWOEdXbmJsWjhvU01ZUHA5L3A4cnpiMFlZTy9PdnRzOU50b09JZjloQmtpYkJZSTl1Ym0Kald1VlFxMW40UzR2UGZVUEkvZ2F6NTNReXpMSTFSTHAxRGQ3ZStUdXR3WnU5cDArQmg0N3F4RFdOd296N0tQeQpaSC9keU9Na2hVa0lMSm9ndUI4c0o3c3RXcGJRRDYrN1ltRVg5VllqZ1AyTnAyenlJRzJpa3hEOTlTaUhva3ZaCkEweCt6dEZabjJyNGhCakV5c3RUMm9HOWV3bFo1bUt4VytBV0V4TzRPcDhjRTduQkxlK3ZQOEhPc1FHRUc3RFAKb1cwdWdwWWxubkV5Wk5rd3ZrOEpSaldlNkU1MWdQUFR0MVNYcndJREFRQUJBb0lCQUNHajhTYVJPRTg0bElpawpwaEo5RUh4YXpiRVVEdzBLUWZPYko2YUYzSGZKTFRublNlK1ZqQ1dZNjFOL2dkcjJGblNWbnVNRmI2Z1EvOGNZCkM3cy9kcncvOVNPSWxKV0xpbnQzZHdCNzkyb1NEZnFWTjkvR2p6NEtDVFhIRHhXeHJUN0dtKzRlTFVweitrZk0KMm9yV2NvMXRMKzF2U0ZWeHZNdVp4M040VUpMeGJISVU0Q2oxVWYvTm52aWlzUVRvdC9YdG9vMGJxYndGZHh3WgpxOFd5ZG9tTmlQWUhkUmJFczdtWmxEYndsNFpaRzJhenpvUkhZM3k3dDA5bllPbzF5MitweWs1TW9xU093cGVNCjZGVzlaTkN6cHFiSVRHLyt5U3YyL3ZMMEFNa2dSSmh0Y1JEeG15bDkvTmVyOXllSWdUcDBGTWpFMlcwUUhDakQKQ3R4Q0R1RUNnWUVBN3lNdEVDcVFJOFZ0MjdKSUw3WGdUQ1lvcUhvOHJUbjhsWEp3b0NBOThFVU5rNjRRZE1jVgpqTzZ4QXJwQ0R1amV1RzRVU1ZMbDhzcDFjMGxRYzc5azdIYVVHa2hDK0FDM2IyVmFuTjZLRk9IeUxRUDJ3TFRGCjErZG00WVdKQStFWWUxT0NBN1RzaUZkNkhONDRFL2RTSnhia3lmL3ByUEFWOStvTlFHVEdRRjhDZ1lFQTdteGgKc25jSXRhcG02VmFLeGJMcFpIaVQ1S255RkFra0pMSDNqVVZXaVFEK2owUXBXY2czNGpNUzRGVFJXa3ZDMzBUSgo1M1d5dHRjTGZ3U0xvSlJ0VzBjNlFGN1ZyRWkxTVh3b0lBSEhOZXVoUTF3aHZtTEdRd3ZUUEFBNnRuUy9pTWJqCmh4amppaUhmaVVPVHZiR3VPVDFacWZ0Vm8xcVZNbjNwM3A5ZHFyRUNnWUVBc3ZsM3E0YS9kQlk1MzFoeUVFc2wKd0xnNmE4VjRqZ2s5RWppaE5DYU5WTHJKcTRKMXpJQ0hqMy9CT1JKZmlEc2ZIWmM5VlpkV2hEeWtaSkUxUmp1egpkQXBYVThoTFhzTmlobHVyMG9YM2dDT09sY1JHcy9sWHJQd0NFcjFYUzNEM1dxMm9POC8zeXg3MVJJL0lGcUZlCmVlVDNmSHNzejRLc1hteHNXSXBUbWk4Q2dZRUFzTGtUSFZaUDFWL3VFZXk4eGRkY1djVnFVZWFKOGNIbzBXNDgKZ0xFeGVER05maUhXeUo2NGxXaW9DREcyVDhpeU5BM24zakdHZXpJZ2FsQ3pNaDV5aEdMaVVZNDVzUTdmaDBOdwo5bkI2K1lPakw2dWRzMkhCZFRiUnByckF5amIxTld1K2dJZTVPTXpzeFBDYkZOTWJ3WCt3ODJiQlRtaTVDQWorCmphM3duckVDZ1lFQW4xRTM1cDRmZzNTT0p3WXFoQjNHcmd3ak9RTU5wVEJYVzJiRVhSRHZtV0I0Z2FqSm5kOFEKRGtRUnVISlpOcTBwYjVYOEF4cmNvSEF5Z2ZJVWtnYUJsUkg3QW80V2tjMTBHcGMyYkV3UTVlZng1ZlcyQkNGbwovQThYS0hKdlpPbUJrUWFNTFZvU2lpaWx2a0pISHYxVGsvK3pxYVFPM09sYmpPdHFUMmdOa2l3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f services.yaml
          kubectl apply -f workloads.yaml
        working-directory: ${{ github.workspace }}
