name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bloodysoon
          password: madrid12489988

      - name: Build and push database image
        uses: docker/build-push-action@v2
        with:
          context: Lab1-bd\Dockerfile
          tags: bloodysoon/laborator_1:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: Lab2-front\Dockerfile
          tags: bloodysoon/laborator_2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f service.yaml
          kubectl apply -f workloads.yaml
