name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bloodysoon
          password: madrid12489988

      - name: Build and push database image
        uses: docker/build-push-action@v2
        with:
          context: ./Lab1-bd
          file: ./Lab1-bd/Dockerfile
          push: true
          tags: bloodysoon/laborator_2:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./Lab2-front
          file: ./Lab2-front/Dockerfile
          push: true
          tags: bloodysoon/laborator_2:latest